# Generated by Django 5.2.4 on 2025-07-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('Фильм', 'movie'), ('Книга', 'book')], max_length=20, verbose_name='Тип'),
        ),
    ]
